# Generated by Django 3.1.4 on 2020-12-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20201210_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
